 /**
   CMP3 Generated Driver File
 
   @Company
     Microchip Technology Inc.
 
   @File Name
     cmp3.c
 
   @Summary
     This is the generated driver implementation file for the CMP3 driver using PIC10 / PIC12 / PIC16 / PIC18 MCUs
 
   @Description
     This source file provides implementations for driver APIs for CMP3.
     Generation Information :
         Product Revision  :  PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.76
         Device            :  PIC16F1779
         Driver Version    :  2.11
     The generated drivers are tested against the following:
         Compiler          :  XC8 2.00 or later
         MPLAB             :  MPLAB X 5.10
 */ 

 /*
    (c) 2018 Microchip Technology Inc. and its subsidiaries. 
    
    Subject to your compliance with these terms, you may use Microchip software and any 
    derivatives exclusively with Microchip products. It is your responsibility to comply with third party 
    license terms applicable to your use of third party software (including open source software) that 
    may accompany Microchip software.
    
    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER 
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY 
    IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS 
    FOR A PARTICULAR PURPOSE.
    
    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP 
    HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO 
    THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL 
    CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT 
    OF FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS 
    SOFTWARE.
*/
 
 /**
   Section: Included Files
 */


#include <xc.h>
#include "cmp3.h"
/**
  Section: CMP3 APIs
*/

void CMP3_Initialize(void)
{
    /* Disable CMP3 interrupt before configuring the CMP3
       control register. Although a comparator is disabled, an interrupt can be
       generated by changing the output polarity with the CxPOL bit of the
       CMxCON0 register,or by switching the comparator on or off with the CxON
       bit of the CMxCON0 register.*/
    PIE2bits.C3IE = 0;

	// C3HYS disabled; C3SP hi_speed; C3ON enabled; C3POL inverted; C3SYNC asynchronous; C3ZLF unfiltered;                          
    CM3CON0 = 0x94;
	
	// C3INTN no_intFlag; C3INTP no_intFlag;                          
    CM3CON1 = 0x00;
	
	// C3NCH CIN2-;                          
    CM3NSEL = 0x02;
	
	// C3PCH FVR_buf2;                          
    CM3PSEL = 0x02;
	
    // Clearing IF flag before enabling the interrupt.
    PIR2bits.C3IF = 0;

    // Enabling CMP3 interrupt.
    PIE2bits.C3IE = 1;
}

bool CMP3_GetOutputStatus(void)
{
	return (CMOUTbits.MC3OUT);
}

//void CMP3_ISR(void)
//{
//    // clear the CMP3 interrupt flag
//    PIR2bits.C3IF = 0;
//}

/**
 End of File
*/
