 /**
   CMP4 Generated Driver File
 
   @Company
     Microchip Technology Inc.
 
   @File Name
     cmp4.c
 
   @Summary
     This is the generated driver implementation file for the CMP4 driver using PIC10 / PIC12 / PIC16 / PIC18 MCUs
 
   @Description
     This source file provides implementations for driver APIs for CMP4.
     Generation Information :
         Product Revision  :  PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.65.2
         Device            :  PIC16F1779
         Driver Version    :  2.11
     The generated drivers are tested against the following:
         Compiler          :  XC8 1.45 or later
         MPLAB             :  MPLAB X 4.15
 */ 

 /*
    (c) 2018 Microchip Technology Inc. and its subsidiaries. 
    
    Subject to your compliance with these terms, you may use Microchip software and any 
    derivatives exclusively with Microchip products. It is your responsibility to comply with third party 
    license terms applicable to your use of third party software (including open source software) that 
    may accompany Microchip software.
    
    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER 
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY 
    IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS 
    FOR A PARTICULAR PURPOSE.
    
    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP 
    HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO 
    THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL 
    CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT 
    OF FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS 
    SOFTWARE.
*/
 
 /**
   Section: Included Files
 */


#include <xc.h>
#include "cmp4.h"
/**
  Section: CMP4 APIs
*/

void CMP4_Initialize(void)
{
    /* Disable CMP4 interrupt before configuring the CMP4
       control register. Although a comparator is disabled, an interrupt can be
       generated by changing the output polarity with the CxPOL bit of the
       CMxCON0 register,or by switching the comparator on or off with the CxON
       bit of the CMxCON0 register.*/
    PIE2bits.C4IE = 0;

	// C4HYS disabled; C4SP hi_speed; C4ON enabled; C4POL inverted; C4SYNC asynchronous; C4ZLF unfiltered;                          
    CM4CON0 = 0x94;
	
	// C4INTN no_intFlag; C4INTP intFlag_pos;                          
    CM4CON1 = 0x02;
	
	// C4NCH CIN0-;                          
    CM4NSEL = 0x00;
	
	// C4PCH DAC1;                          
    CM4PSEL = 0x05;
	
    // Clearing IF flag before enabling the interrupt.
    PIR2bits.C4IF = 0;

    // Enabling CMP4 interrupt.
    PIE2bits.C4IE = 1;
}

bool CMP4_GetOutputStatus(void)
{
	return (CMOUTbits.MC4OUT);
}

void CMP4_ISR(void)
{
    // clear the CMP4 interrupt flag
    PIR2bits.C4IF = 0;
}

/**
 End of File
*/
